# CAUTION: This file is generated automatically, any customisation will be lost.

package:
  name: coolprop
  version: 6.0.1dev


source:
  git_url: https://github.com/CoolProp/CoolProp.git


#build:
#  script: python setup.py install [not win]
#  script: "%PYTHON%" setup.py install & if errorlevel 1 exit 1 [win]

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - pandas
    - cython

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas

test:
  # Python imports
  imports:
    - CoolProp
#    #- CoolProp.GUI
#    #- CoolProp.Plots
#    - CoolProp.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    # - nose
    - numpy
    - scipy
    - matplotlib
    - pandas
    - cython
    - nose

about:
  home: http://www.coolprop.org
  license: MIT
  summary: Open-source thermodynamic and transport properties database
