package:
  name: eigen
  version: 3.2.1

source:
  fn: eigen-3.2.1.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.2.1.tar.gz

requirements:
  build:
    - cmake
    - gcc ==4.8.2

about:
  home: http://eigen.tuxfamily.org
  license: MPL2
