package:
    name: lpsolve55
    version: 5.5.1

source:
    git_url: https://github.com/amarkpayne/lp_solve_python_3x.git

build:
    number: 3

requirements:
    build:
        - python
        - setuptools
        - numpy
        - lpsolve

    run:
        - python
        - numpy
        - lpsolve

test:
    imports:
        - lpsolve55

about:
    home: http://lpsolve.sourceforge.net/
    license: LGPL
    summary: "Linear Program Solver, Python Interface to lpsolve"
