
package:
    name: openbabel
    version: 2.3.2

source:
    fn: openbabel-2.3.2.tar.gz
    url: http://sourceforge.net/projects/openbabel/files/openbabel/2.3.2/openbabel-2.3.2.tar.gz
    sha1: b8831a308617d1c78a790479523e43524f07d50d

    patches:
        - ob-2-3-2-patch.diff # [osx]
        - ob-mavericks.patch  # [osx]
        - pybel-test.patch
        - fix_library_path_search.diff
        - fix_data_path.diff
        - fix_babel_test_paths.diff
        - fix_pythontest.diff # [win]
        - libxml_windows_patch.diff # [win]
        - windows_swig_comment.diff # [win]
        - absence_of_cat_windows.diff # [win]
        - dont_create_extension.diff # [win]

build:
    number: 4
    detect_binary_files_with_prefix: true

requirements:
    build:
        - cmake      
        - pkg-config # [unix]
        - zlib      
        - swig
        - eigen
        - bzip2 
        - python 
        - zlib 
        - libxml2
        - cairo [unix]
    run:
        - python 
        - eigen
        - zlib
        - libxml2
        - cairo [unix]
test:
  source_files:
    - '*'
  imports:
    - openbabel
    - pybel
  commands:
    - cd $SRC_DIR/test ; python test_pybel.py [unix]
    - cd $SRC_DIR/test ; python testbabel.py [unix]
    - cd $SRC_DIR/test ; python testkekule.py [unix]
    - cd $SRC_DIR/test ; python testbindings.py [unix]
    - cd $SRC_DIR/test ; python testexample.py [unix]
    - python run_test.py [win]
    - python %SRC_DIR%\test\testbindings.py [win]
    - python %SRC_DIR%\test\testexample.py [win]

about:
    home: http://www.openbabel.org/
    license: GPLv2
    summary: "A chemical toolbox designed to speak the many languages of chemical data"
