# This file created for conda-build 3.10.9
#
# ------------------------------------------------

package:
    name: py3dmol
    version: '0.7.2'

requirements:
    build:
        - python
    run:
        - python
        - IPython
test:
    imports:
        - py3Dmol
about:
    home: https://github.com/3dmol/3Dmol.js/tree/master/py3Dmol
    license: MIT
    summary: A simple IPython/Jupyter widget to embed an interactive 3Dmol.js viewer in a notebook.


