package:
  name: py2cairo
  version: 1.10.0

source:
  fn: py2cairo-1.10.0.tar.bz2
  url: http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2
  md5: 20337132c4ab06c1146ad384d55372c5
  
  patches:
    - fix-waf-extension.patch

build:
  number: 2

requirements:
  build:
    - pkg-config
    - cairo
    - python
  run:
    - pkg-config
    - cairo
    - python

about:
  home: http://cairographics.org/pycairo/
  license: LGPL 2.1 and MPL 1.1
