{% set version = "0.5.3" %}
{% set name = "julia" %}

package:
  name: pyjulia
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b13207125709fdba069a25c4e54ff366f0bc308807b2aa0f3b66924101799c58

requirements:
  build:
    - python>=3.7.1
    - pip
    - julia>=1.1.1
  run:
    - python>=3.7.1
    - julia>=1.1.1

test:
  imports:
    - julia
  commands:
    - python -c "from julia.api import Julia; jl = Julia(compiled_modules=False); from julia import Main"

about:
  home: https://github.com/JuliaPy/pyjulia
  license: MIT
  license_file: 'LICENSE.md'
  license_family: MIT
  summary: "python interface to julia"

