{% set version = "0.5.1" %}
{% set name = "julia" %}

package:
  name: pyjulia
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9660819b4326d107009000bb0d283634a9b19e5de70d89680fb06127121d05d6

requirements:
  build:
    - python>=3
    - pip
    - julia>=1.1
  run:
    - python>=3
    - julia>=1.1

test:
  commands:
    - python-jl -c 'import julia; julia.Julia()'
  imports:
    - julia

about:
  home: https://github.com/JuliaPy/pyjulia
  license: MIT
  license_file: 'LICENSE.md'
  license_family: MIT
  summary: "python interface to julia"

