# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Apr 27 16:06:48 2020
# ------------------------------------------------

package:
    name: julia
    version: 1.1.1
source:
    fn: v1.1.1.tar.gz
    sha256: 0155a33448cb2334ae7487a35a2416a4205da4541b90fc9f97208da11e273c9e
    url: https://github.com/JuliaLang/julia/archive/v1.1.1.tar.gz
build:
    number: '1'
    string: rmg_1
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_0
        - binutils_linux-64 2.34 hc952b39_18
        - ca-certificates 2020.4.5.1 hecc5488_0
        - cmake-binary 3.9.1 h2f8e2a0_1
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_18
        - gfortran_impl_linux-64 7.3.0 hdf63c60_5
        - gfortran_linux-64 7.3.0 h553295d_18
        - gxx_impl_linux-64 7.3.0 hdf63c60_5
        - gxx_linux-64 7.3.0 h553295d_18
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgfortran-ng 7.3.0 hdf63c60_5
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - perl 5.26.2 h516909a_1006
        - python 2.7.15 h5a48372_1011_cpython
        - python_abi 2.7 1_cp27mu
        - readline 8.0 hf8c457e_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - zlib 1.2.11 h516909a_1006
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - arpack 3.7.0 hc6cf775_1
        - ca-certificates 2020.4.5.1 hecc5488_0
        - curl 7.64.0 h646f8bb_0
        - fftw 3.3.8 nompi_h7f3a6c3_1110
        - gmp 6.2.0 he1b5a44_2
        - krb5 1.16.3 hc83ff2d_1000
        - libblas 3.8.0 8_h6e990d7_netlib
        - libcblas 3.8.0 8_h6e990d7_netlib
        - libcurl 7.64.0 h01ee5af_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgfortran-ng 7.3.0 hdf63c60_5
        - libgit2 0.27.8 hbd8068c_0
        - libgomp 9.2.0 h24d8f2e_2
        - liblapack 3.8.0 8_h6e990d7_netlib
        - libssh2 1.8.0 h1ad7b7a_1003
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - metis 5.1.0 he1b5a44_1005
        - mpfr 4.0.2 he80fd80_1
        - ncurses 6.1 hf484d3e_1002
        - openlibm 0.5.4 h14c3975_1000
        - openspecfun 0.5.3 hc99cbb1_1001
        - openssl 1.0.2u h516909a_0
        - patchelf 0.10 he1b5a44_0
        - pcre2 10.23 2
        - suitesparse 5.6.0 h717dc36_0
        - tbb 2020.1 hc9558a2_0
        - tk 8.6.10 hed695b0_0
        - zlib 1.2.11 h516909a_1006
    run:
        - arpack >=3.7.0,<3.7.1.0a0
        - arpack >=3.7.0,<3.7.1.0a0
        - curl >=7.64.0,<8.0a0
        - fftw >=3.3.8,<4.0a0
        - gmp >=6.2.0,<7.0a0
        - gmp >=6.2.0,<7.0a0
        - libblas >=3.8.0,<4.0a0
        - libcblas >=3.8.0,<4.0a0
        - libgcc-ng >=7.3.0
        - libgfortran-ng >=7,<8.0a0
        - libgit2 >=0.27.8,<0.28.0a0
        - liblapack >=3.8.0,<3.9.0a0
        - libstdcxx-ng >=7.3.0
        - mpfr >=4.0.2,<5.0a0
        - mpfr >=4.0.2,<5.0a0
        - openlibm 0.5.4.*
        - openspecfun 0.5.3.*
        - pcre2 10.23.*
        - suitesparse >=5.6.0,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - julia -e 'Base.runtests("LibGit2/online Pkg/pkg")'
    requires:
        - perl
about:
    home: http://julialang.org/
    license: MIT
    license_file: LICENSE.md
    summary: A high-performance dynamic programming language for data science
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mjohnson541
