{% set name = "acat" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acat-{{ version }}.tar.gz
  sha256: dbae28df88402beb8b46577b1b0b7a160835dfe958f91fd17924de7095328a0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase
    - networkx >=2.4
    - python >=3.6

test:
  imports:
    - acat

about:
  home: https://gitlab.com/asm-dtu/acat
  summary: Alloy Catalysis Automated Toolkit
  license: LGPL-3.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - mjohnson541
