package:
  name: mopac
  version: 2016

source:
  fn: MOPAC2016_for_Macintosh.zip # [osx]
  url: http://openmopac.net/MOPAC2016_for_Macintosh.zip # [osx]
  md5: 40adbeaccd02d0980a6dc29a5e0d74f2 # [osx]
  
  
  fn: MOPAC2016_for_Linux_64_bit.zip # [linux64]
  url: http://openmopac.net/MOPAC2016_for_Linux_64_bit.zip # [linux64]
  md5: 83ddd4a87760bc6f793237923b69e935 # [linux64]

  fn: MOPAC2016_for_Linux_32_bit.zip # [linux32]
  url: http://openmopac.net/MOPAC2016_for_Linux_32_bit.zip # [linux32]
  md5: ca976f298d5984c2f2b04a8955eadf28 # [linux32]
  
  fn: MOPAC2016_standalone_for_WINDOWS_64_bit.zip [win64]
  url:  http://openmopac.net/MOPAC2016_standalone_for_WINDOWS_64_bit.zip [win64]
  
  fn: MOPAC2016_standalone_for_WINDOWS_32_bit.zip [win32]
  url: http://openmopac.net/MOPAC2016_standalone_for_WINDOWS_32_bit.zip [win32]
  
build:
  number: 1
  binary_relocation: false

test:
  commands:
    - mopac

about:
  home: http://openmopac.net
  license: executables are available FREE for academic, not-for-profit use