# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /Users/runner/runners/2.166.4/work/1/s/recipe, last modified Mon Apr 27 16:06:50 2020
# ------------------------------------------------

package:
    name: julia
    version: 1.4.2
build:
    number: '1'
    string: rmg_1 
about:
    summary: julia from julialang
extra:
    recipe-maintainers:
        - mjohnson541
