# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /Users/runner/runners/2.166.4/work/1/s/recipe, last modified Mon Apr 27 16:06:50 2020
# ------------------------------------------------

package:
    name: julia
    version: 1.1.1
source:
    fn: v1.1.1.tar.gz
    sha256: 0155a33448cb2334ae7487a35a2416a4205da4541b90fc9f97208da11e273c9e
    url: https://github.com/JuliaLang/julia/archive/v1.1.1.tar.gz
build:
    number: '1'
    string: rmg_1
requirements:
    build:
        - ca-certificates 2020.4.5.1 hecc5488_0
        - cctools 927.0.2 h5ba7a2e_4
        - clang 9.0.1 default_hf57f61e_0
        - clang-tools 9.0.1 default_hf57f61e_0
        - clang_osx-64 9.0.1 h05bbb7f_0
        - clangxx 9.0.1 default_hf57f61e_0
        - clangxx_osx-64 9.0.1 h05bbb7f_0
        - cmake-binary 3.9.1 h19c0166_1
        - compiler-rt 9.0.1 h6a512c6_3
        - compiler-rt_osx-64 9.0.1 h99342c6_3
        - gfortran_impl_osx-64 7.3.0 hf4212f2_2
        - gfortran_osx-64 7.3.0 h22b1bf0_10
        - gmp 6.2.0 h4a8c4bd_2
        - isl 0.19 0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 h1af66ff_2
        - libffi 3.2.1 h4a8c4bd_1007
        - libgfortran 4.0.0 2
        - libiconv 1.15 h0b31af3_1006
        - libllvm9 9.0.1 h7475705_1
        - llvm-openmp 10.0.0 h28b9765_0
        - mpc 1.1.0 h4160ff4_1007
        - mpfr 4.0.2 h65ac59c_1
        - ncurses 6.1 h0a44026_1002
        - openssl 1.1.1g h0b31af3_0
        - perl 5.26.2 haec8ef5_1006
        - python 2.7.15 h8e446fc_1011_cpython
        - python_abi 2.7 1_cp27m
        - readline 8.0 hcfe32e1_0
        - sqlite 3.30.1 h93121df_0
        - tapi 1000.10.8 ha1b3eb9_4
        - tk 8.6.10 hbbe82c9_0
        - zlib 1.2.11 h0b31af3_1006
    host:
        - arpack 3.7.0 hbb27dc6_1
        - ca-certificates 2020.4.5.1 hecc5488_0
        - curl 7.64.0 heae2a1f_0
        - fftw 3.3.8 nompi_h44ae4c8_1110
        - gmp 6.2.0 h4a8c4bd_2
        - krb5 1.16.3 h24a3359_1000
        - libblas 3.8.0 8_h1ddc27c_netlib
        - libcblas 3.8.0 8_h1ddc27c_netlib
        - libcurl 7.64.0 h76de61e_0
        - libcxx 10.0.0 h1af66ff_2
        - libedit 3.1.20170329 hcfe32e1_1001
        - libgfortran 4.0.0 2
        - libgit2 0.27.8 hab25c6f_0
        - libiconv 1.15 h0b31af3_1006
        - liblapack 3.8.0 8_h1ddc27c_netlib
        - libosxunwind 0.0.5 h04f5b5a_1000
        - libssh2 1.8.0 hf30b1f0_1003
        - llvm-openmp 10.0.0 h28b9765_0
        - metis 5.1.0 h4a8c4bd_1005
        - mpfr 4.0.2 h65ac59c_1
        - ncurses 6.1 h0a44026_1002
        - openlibm 0.5.4 h1de35cc_1000
        - openspecfun 0.5.3 hfcebdee_1001
        - openssl 1.0.2u h0b31af3_0
        - pcre2 10.23 2
        - suitesparse 5.6.0 h0e59142_0
        - tbb 2019.9 ha1b3eb9_1
        - tk 8.6.10 hbbe82c9_0
        - zlib 1.2.11 h0b31af3_1006
    run:
        - arpack >=3.7.0,<3.7.1.0a0
        - arpack >=3.7.0,<3.7.1.0a0
        - curl >=7.64.0,<8.0a0
        - fftw >=3.3.8,<4.0a0
        - gmp >=6.2.0,<7.0a0
        - gmp >=6.2.0,<7.0a0
        - libblas >=3.8.0,<4.0a0
        - libcblas >=3.8.0,<4.0a0
        - libcxx >=9.0.1
        - libgfortran >=4.0.0,<5.0.0.a0
        - libgit2 >=0.27.8,<0.28.0a0
        - liblapack >=3.8.0,<3.9.0a0
        - libosxunwind
        - mpfr >=4.0.2,<5.0a0
        - mpfr >=4.0.2,<5.0a0
        - openlibm 0.5.4.*
        - openspecfun 0.5.3.*
        - pcre2 10.23.*
        - suitesparse >=5.6.0,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - julia -e 'Base.runtests("LibGit2/online Pkg/pkg")'
    requires:
        - perl
about:
    home: http://julialang.org/
    license: MIT
    license_file: LICENSE.md
    summary: A high-performance dynamic programming language for data science
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mjohnson541
