{% set version = "0.1.2" %}
{% set name = "pyrms" %}

package:
  name: pyrms
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2750e5f714baa8430de616f17a838759c3d7a4b53144fc3bf8efa5702b4b673d

build:
    number: '1'
    string: rmg_1

requirements:
  build:
    - python=3.7
    - pip
  run:
    - python=3.7
    - julia>=1
    - diffeqpy
    - pyjulia
    - rmg>=3.0.0
    - rdkit
    - pydot
    - matplotlib
    - pyyaml

test:
  imports:
    - pyrms
  #commands:
  #  - python -c "from julia.api import Julia; jl = Julia(compiled_modules=False); from pyrms import rms"
  #  - python-jl -c "from pyrms import rms"
  #  - nosetests pyrms/pyrms/rmsTest.py

about:
  home: https://github.com/ReactionMechanismGenerator/pyrms
  license: MIT
  #license_file: 'LICENSE.md'
  #license_family: MIT
  summary: "python interface to ReactionMechanismSimulator"

