{% set version = "1.0.2" %}
{% set name = "pyrms" %}

package:
  name: pyrms
  version: {{ version }}

source:
  git_rev: v1.0.2 # change to the version on GitHub to build
  git_url: https://github.com/ReactionMechanismGenerator/pyrms.git

build:
    number: '1'
    string: rmg_1 # change to no_rmg_dep if building for RMG

requirements:
  build:
    - python=3.7
    - pip
  run:
    - python=3.7
    - julia>=1.3
    - diffeqpy
    - pyjulia
    - rmg>=3.0.0 # remove this if building for RMG
    - rdkit
    - pydot
    - matplotlib
    - pyyaml

test:
  imports:
    - pyrms
  #commands:
  #  - python -c "from julia.api import Julia; jl = Julia(compiled_modules=False); from pyrms import rms"
  #  - python-jl -c "from pyrms import rms"
  #  - nosetests pyrms/pyrms/rmsTest.py

about:
  home: https://github.com/ReactionMechanismGenerator/pyrms
  license: MIT
  #license_file: 'LICENSE.md'
  #license_family: MIT
  summary: "python interface to ReactionMechanismSimulator"

