{% set version = "0.1.0" %}
{% set name = "pyrms" %}

package:
  name: pyrms
  version: {{ version }}

source:
  git_rev: installfcn
  git_url: https://github.com/ReactionMechanismGenerator/pyrms.git

build:
    number: '1'
    string: rmg_1

requirements:
  build:
    - python=3.7
  run:
    - python=3.7
    - julia>=1
    - diffeqpy
    - pyjulia
    - rmg>=3.0.0
    - rdkit
    - pydot
    - matplotlib
    - pyyaml

test:
  imports:
    - pyrms
  #commands:
  #  - python -c "from julia.api import Julia; jl = Julia(compiled_modules=False); from pyrms import rms"
  #  - python-jl -c "from pyrms import rms"
  #  - nosetests pyrms/pyrms/rmsTest.py

about:
  home: https://github.com/ReactionMechanismGenerator/pyrms
  license: MIT
  #license_file: 'LICENSE.md'
  #license_family: MIT
  summary: "python interface to ReactionMechanismSimulator"

