{% set version = "0.1.2" %}
{% set name = "pyrms" %}

package:
  name: pyrms
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3a8929d5c66a80cc17469c3d82991182d566ad53c5b9d427d4f94ce2bcf73e5

build:
    number: '1'
    string: rmg_1

requirements:
  build:
    - python=3.7
    - pip
  run:
    - python=3.7
    - julia>=1.3
    - diffeqpy
    - pyjulia
    - rmg>=3.0.0
    - rdkit
    - pydot
    - matplotlib
    - pyyaml

test:
  imports:
    - pyrms
  #commands:
  #  - python -c "from julia.api import Julia; jl = Julia(compiled_modules=False); from pyrms import rms"
  #  - python-jl -c "from pyrms import rms"
  #  - nosetests pyrms/pyrms/rmsTest.py

about:
  home: https://github.com/ReactionMechanismGenerator/pyrms
  license: MIT
  #license_file: 'LICENSE.md'
  #license_family: MIT
  summary: "python interface to ReactionMechanismSimulator"

