# This file created by conda-build 2.0.8
# meta.yaml template originally from:
# /Users/mjliu/Dropbox (MIT)/Research/anaconda/lpsolve, last modified Thu Nov  3 17:02:02 2016
# ------------------------------------------------

package:
    name: lpsolve
    version: 5.5.2.5
source:
    fn: lp_solve_5.5.2.5_source.tar.gz
    md5: 3be57261fc41dd8e210f54017220d5f7
    url: https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.5/lp_solve_5.5.2.5_source.tar.gz
build:
    number: '0'
test:
    files:
        - demo.c
about:
    home: http://lpsolve.sourceforge.net/5.5/
    license: LGPL
extra:
    recipe-maintainers:
        - snorfalorpagus
