# This file created by conda-build 2.0.8
# meta.yaml template originally from:
# /Users/mjliu/Dropbox (MIT)/Research/anaconda/lpsolve, last modified Thu Nov  3 17:02:02 2016
# ------------------------------------------------

package:
    name: lpsolve
    version: 5.5.2.5
source:
    git_url: https://github.com/amarkpayne/lp_solve_python_3x.git
build:
    number: 2
test:
    files:
        - demo.c
about:
    home: http://lpsolve.sourceforge.net/5.5/
    license: LGPL
extra:
    recipe-maintainers:
        - snorfalorpagus
