name: Build Packages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - stable
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        recipe: [symmetry]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          conda-solver: libmamba
          auto-activate-base: true
          activate-environment: ""
      - name: Install Build Tools
        run: conda install python anaconda-client conda-build
      - name: Configure Auto-Upload
        if: github.ref == 'refs/heads/stable'
        run: |
          conda config --set anaconda_upload yes
      - name: Build Binary
        run: |
          # set a default value to the conda_token if needed (like from forks)
          : "${CONDA_TOKEN:=${{ secrets.ANACONDA_TOKEN }}}"
          : "${CONDA_TOKEN:=default_value}"
          echo "CONDA_TOKEN=$CONDA_TOKEN" >> $GITHUB_ENV
          conda config --add channels conda-forge
          conda config --add channels rmg
          conda build --token $CONDA_TOKEN --user rmg ${{ matrix.recipe }}
