package:
  name: pydot
  version: "2.0.1"

source:
  git_url: https://github.com/connie/pydot.git

requirements:
  build:
    - pyparsing
    - python
    - setuptools

  run:
    - graphviz
    - pyparsing
    - python

test:
  source_files:
    - '*'
  imports:
    - pydot

  commands:
    - cd $SRC_DIR/test ; python pydot_unittest.py [unix]
    - cd %SRC_DIR%\test [win]
    - python %SRC_DIR%\test\pydot_unittest.py [win]

about:
  home: https://github.com/connie/pydot
  license: MIT
  summary: 'Python interface to the Graphviz Dot language. With support for Python 3-x and compatibility with pyparsing >=2'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
